var my_result = document.createElement('div');
my_result.id = "my_result";
var result =document.getElementById('result');
my_result.innerHTML = [
	'<div id="cao_context">',

			'<div class="cao_column">',
				'<h2>',
					'<a href="###">',
						'中央气象台网站启用新域名www.nmc.cn',
					'</a>',
				'</h2>',
				'<div class="cao_img fl_left">',
					'<a href="###">',
						'<img src="img/气象台.png" alt="天气网" />',
					'</a>',
				'</div>',
				'<div class="cao_text fl_left">中央气象台官方网站权威发布台风、暴雨、寒潮、高温、沙尘暴、大雾等各类灾害性的预报警报。提供<em>天气</em>预报、<em>天气</em>实况、降水量预报、强对流<em>天气</em>预报、农业气象、海洋...</div>',
				'<div class="cao_foot fl_left">',
					'<div class="fl_left">',
						'<a href="###">www.nmc.cn/&nbsp;</a>',
					'</div>',
				'</div>',
				'<div class="fl_left cao_foot_nav">',
					'<ul>',
						'<li>',
							'<a href="###">',
								'<span class="cao_triangle"></span>',
							'</a>',
							'<ul class="cao_nav">',
								'<span class="cao_triangke_copy"></span>',
								'<li>',
									'<a href="###">收藏</a>',
								'</li>',
								'<li>',
									'<a href="###">分享</a>',
								'</li>',
								'<li>',
									'<a href="###">评价</a>',
								'</li>',
								'<li>',
									'<a href="###">举报</a>',
								'</li>',
							'</ul>',
						'</li>',
					'</ul>',
				'</div>',
				'<div class="fl_left">',
					'&nbsp;-&nbsp;',
					'<span class="cao_link">',
						'<a href="###">百度快照</a>',
					'</span>',
					'&nbsp;-&nbsp;',
					'<span class="cao_link">',
						'<a href="###">评价</a>',
					'</span>',	
				'</div>',
				'<div class="clear"></div>',
			'</div>',
			'<div class="cao_column">',
				'<h2>',
					'<a href="###">',
						'<em>天气</em>预报查询一周_全国<em>天气</em>预报15天查询-搜狗<em>天气</em>预报',
					'</a>',
				'</h2>',
				
				'<div class="cao_text_1 fl_left">搜狗<em>天气</em>预报提供全国各大城市和旅游景点<em>天气</em>预报查询服务,帮您了解未来一周、10天,15天的<em>天气</em>情况,同时还包含生活指数、空气质量及<em>天气</em>新闻等内容。实时更新<em>天气</em>预报...</div>',
				'<div class="cao_foot fl_left">',
					'<div class="fl_left">',
						'<a href="###">tianqi.sogou.com/&nbsp;</a>',
					'</div>',
				'</div>',
				'<div class="fl_left cao_foot_nav">',
					'<ul>',
						'<li>',
							'<a href="###">',
								'<span class="cao_triangle"></span>',
							'</a>',
							'<ul class="cao_nav">',
								'<span class="cao_triangke_copy"></span>',
								'<li>',
									'<a href="###">收藏</a>',
								'</li>',
								'<li>',
									'<a href="###">分享</a>',
								'</li>',
								'<li>',
									'<a href="###">评价</a>',
								'</li>',
								'<li>',
									'<a href="###">举报</a>',
								'</li>',
							'</ul>',
						'</li>',
					'</ul>',
				'</div>',
				'<div class="fl_left">',
					'&nbsp;-&nbsp;',
					'<span class="cao_link">',
						'<a href="###">百度快照</a>',
					'</span>',
					'-',
					'<span class="cao_link">',
						'<a href="###">1718条评价</a>',
					'</span>',	
				'</div>',
				'<div class="clear"></div>',
			'</div>',
			'<div class="cao_column">',
				'<h2>',
					'<a href="###">',
						'<em>天气</em>_百度百科',
					'</a>',
				'</h2>',
				'<div class="cao_img_1 fl_left">',
					'<a href="###">',
						'<img src="img/百科.png" alt="天气网" />',
					'</a>',
				'</div>',
				'<div class="cao_text fl_left"><em>天气</em>是指某一个地区距离地表较近的大气层在短时间内的具体状态。而<em>天气</em>现象则是指发生在大气中的各种自然现象，即...</div>',
				'<ul id="more" >',
					'<li>',
						'<a href="###">种类</a>',
					'</li>',
					'<li>',
						'<a href="###">风</a>',
					'</li>',
					'<li>',
						'<a href="###">云</a>',
					'</li>',
					'<li>',
						'<a href="###">雾</a>',
					'</li>',
					'<li>',
						'<a href="###">雨</a>',
					'</li>',
					'<li>',
						'<a href="###">雪</a>',
					'</li>',
					'<li>',
						'<a href="###"><em>天气</em>符号</a>',
					'</li>',
					'<li>',
						'<a href="###">霜</a>',
					'</li>',
					'<li>',
						'<a href="###">雷雨</a>',
					'</li>',
					'<li>',
						'<a href="###">历史</a>',
					'</li>',
					'<li>',
						'<a href="###">更多>></a>',
					'</li>',
				'</ul>',
				'<a href="" id="meaning" class="fl_left">查看“<em>天气</em>”全部8个含义>></a>',
				'<div class="cao_foot fl_left">',
					'<div class="fl_left">',
						'<a href="###">baike.baidu.com/&nbsp;</a>',
					'</div>',
				'</div>',
				'<div class="fl_left cao_foot_nav">',
					'<ul>',
						'<li>',
							'<a href="###">',
								'<span class="cao_triangle"></span>',
							'</a>',
							'<ul class="cao_nav">',
								'<span class="cao_triangke_copy"></span>',
								'<li>',
									'<a href="###">收藏</a>',
								'</li>',
								'<li>',
									'<a href="###">分享</a>',
								'</li>',
								'<li>',
									'<a href="###">评价</a>',
								'</li>',
								'<li>',
									'<a href="###">举报</a>',
								'</li>',
							'</ul>',
						'</li>',
					'</ul>',
				'</div>',
				'<div class="fl_left">',
					'&nbsp;-&nbsp;',
					'<span class="cao_link">',
						'<a href="###">','<img src="https://www.baidu.com/cache/global/img/aladdinIcon-1.0.gif" alt="FALSE" /></a>',
					'</span>',
				'</div>',
				'<div class="clear"></div>',
			'</div>',
			'<div class="cao_column">',
				'<h2>',
					'<a href="###">',
						'<em>天气</em>预报中的阴是下雨的意思吗,还是指不下雨,就<em>天气</em>很..._百度知道',
					'</a>',
				'</h2>',
				'<div class="cao_mark">',
					'5个回答 - 最新回答: 2017年05月26日 - 19人觉得有用',
				'</div>',
				'<div class="cao_text_1 fl_left"><span id="cao_mark_green">【专业】</span>答案:<em>天气</em>预报中的阴天是一种<em>天气</em>现象,阴天(overcast):天空中,低云总云量在8/10及以上,阳光很少或不能透过云层, 天色阴暗的天空状况。<em>天气</em>预报中的阴不是...</div>',
				'<div id="cao_konw_more">',
					'<a href="###">更多关于<em>天气</em>的问题</a>',
				'</div>',
				'<div class="cao_foot fl_left">',
					'<div class="fl_left">',
						'<a href="###">tianqi.sogou.com/&nbsp;</a>',
					'</div>',
				'</div>',
				'<div class="fl_left cao_foot_nav">',
					'<ul>',
						'<li>',
							'<a href="###">',
								'<span class="cao_triangle"></span>',
							'</a>',
							'<ul class="cao_nav">',
								'<span class="cao_triangke_copy"></span>',
								'<li>',
									'<a href="###">收藏</a>',
								'</li>',
								'<li>',
									'<a href="###">分享</a>',
								'</li>',
								'<li>',
									'<a href="###">评价</a>',
								'</li>',
								'<li>',
									'<a href="###">举报</a>',
								'</li>',
							'</ul>',
						'</li>',
					'</ul>',
				'</div>',
				'<div class="fl_left">',
					'&nbsp;-&nbsp;',
					'<span class="cao_link">',
						'<a href="###">百度快照</a>',
					'</span>',
					'&nbsp;-&nbsp;',
					'<span class="cao_link">',
						'<a href="###">1718条评价</a>',
					'</span>',	
				'</div>',
				'<div class="clear"></div>',
			'</div>',
		'</div>',
].join('');
result.appendChild( my_result );
